export const products = [
  {
    id: 101,
    title: 'Nike Air Max 270',
    description:
      'Step into comfort and style with the Nike Air Max 270. Designed with a sleek silhouette and bold Air cushioning for all-day wear.',
    price: 129.99,
    subCategory: 'Shoes',
    category: 'shoes',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/przhlilttuqiis7no3rr/W+AIR+MAX+270.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/cb1951e7-0600-4f7a-9b26-12be8cd2bd01/W+AIR+MAX+270.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/44fdb67b-6626-4463-85e3-8c181c75c8b1/W+AIR+MAX+270.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/162a3c7d-d32b-46dd-b9d1-631494f6f2db/W+AIR+MAX+270.png',
    ],
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Red'],
    rating: 4.5,
    stock: 20,
    isFeatured: true,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'John Doe',
        rating: 5,
        comment: 'Super comfortable! Love the design.',
      },
      {
        id: 2,
        user: 'Sarah Smith',
        rating: 4,
        comment: 'Great shoe but fits slightly narrow.',
      },
    ],
  },
  {
    id: 102,
    title: 'Nike Dri-FIT Legend T-Shirt',
    description:
      'The Nike Dri-FIT Legend Tee keeps you dry and comfortable with sweat-wicking fabric. Perfect for workouts or casual wear.',
    price: 30.0,
    subCategory: 'Tops',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/h_439,c_limit/f06109b3-20a4-4fbd-a9d7-6a4220c17d15/chelsea-fc-2025-26-stadium-home-dri-fit-football-replica-shirt-5zMBHx.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/45a905ad-5758-49cf-b98e-be2a3e34278a/CFC+M+NK+DF+JSY+SS+STAD+HM.png',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Gray', 'Blue'],
    rating: 4.3,
    stock: 50,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 103,
    title: 'Nike Sportswear Club Fleece Shorts',
    description:
      'Soft, comfortable fleece shorts for casual days. Standard fit with a drawcord waist for adjustable comfort.',
    price: 45.0,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/636e3c84-48fd-4549-bd2c-07f794f85c4c/AS+M+NK+CLUB+FLOW+FT+SHORT.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3ec383a9-b786-4758-9b12-ad9c3304cef4/AS+M+NK+CLUB+FLOW+FT+SHORT.png',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Gray', 'Black'],
    rating: 4.7,
    stock: 35,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 104,
    title: "Nike Air Force 1 '07",
    description:
      'The legendary AF1 with a fresh, clean style. Durable leather upper and classic Air-Sole cushioning.',
    price: 110.0,
    subCategory: 'shoes',
    category: 'shoes',
    gender: 'women',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/654ae3ec-14af-4fe4-b477-1ec65950247b/W+AIR+ZOOM+PEGASUS+41.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/63f2e39d-2461-4067-8199-8f5f8da3cc22/W+AIR+ZOOM+PEGASUS+41.png',
    ],
    sizes: ['6', '7', '8', '9', '10'],
    colors: ['White', 'Pink', 'Black'],
    rating: 4.8,
    stock: 18,
    isFeatured: true,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Emily Ray',
        rating: 5,
        comment: 'Iconic and always stylish!',
      },
    ],
  },
  {
    id: 105,
    title: 'Nike Vomero 18',
    description:
      'Breathable comfort for little feet. Soft cushioning and durable design for everyday wear.',
    price: 55.0,
    subCategory: 'shoes',
    category: 'shoes',
    gender: 'kids',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6787738f-38d6-431e-9405-26b0e0a545c8/NIKE+VOMERO+18+%28GS%29.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9cdd1dad-aa25-4c40-8808-23e16dd16cbe/NIKE+VOMERO+18+%28GS%29.png',
    ],
    sizes: ['1', '2', '3', '4', '5'],
    colors: ['Blue', 'Red', 'Green'],
    rating: 4.6,
    stock: 40,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 106,
    title: 'Nike Club Fleece Hoodie',
    description:
      'Soft, warm and made to move, this hoodie keeps you cozy and comfortable all day.',
    price: 60.0,
    subCategory: 'Tops',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/163523d9-27be-44fb-b0ae-dc19c6975403/AS+M+NK+PF+GPX+PO+HOODIE+2.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f556d3fe-9aab-4f60-9220-3311552af754/AS+M+NK+PF+GPX+PO+HOODIE+2.png',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Olive'],
    rating: 4.4,
    stock: 28,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 107,
    title: 'Nike Pro Sculpt',
    description:
      'Supportive and sweat-wicking, these leggings are ideal for high-intensity workouts.',
    price: 45.0,
    subCategory: 'Bottoms',
    category: 'clothing',
    gender: 'women',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7d9aff3e-3f4d-4d6c-9a8f-332db91a97b8/AS+W+NP+SCULPT+DF+HR+TIGHT.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed74e81d-3d4f-401c-be26-80501b58487a/AS+W+NP+SCULPT+DF+HR+TIGHT.png',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Gray', 'Maroon'],
    rating: 4.2,
    stock: 42,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 108,
    title: "Nike Kids' Pullover Hoodie",
    description:
      'A lightweight hoodie made for everyday play and layered comfort.',
    price: 35.0,
    subCategory: 'Tops',
    category: 'clothing',
    gender: 'kids',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/2c5636b9-a551-4e0c-8711-50fb01427b0c/M+J+BRK+FLC+PO+LB.png',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cf8e3f3b-3dd7-45b7-9dd0-b09e176366b3/AS+M+NK+CLUB+FT+OVERSIZED+PO+H.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/07e155bd-ccd0-4463-bbec-69aa26941dca/M+J+BRK+FLC+PO+LB.png',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blue', 'Gray'],
    rating: 4.0,
    stock: 33,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 109,
    title: 'Nike Everyday Plus Socks (3 Pairs)',
    description:
      'Soft, sweat-wicking comfort in a classic crew style with arch support.',
    price: 18.0,
    subCategory: 'Accessories',
    category: 'accessories',
    gender: 'unisex',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/7cf58584-3b41-420d-83af-20c91774965a/U+NK+EVERYDAY+CSH+ANKL+3PR+132.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/68c250f2-451a-47d4-a5be-de7cc13dd82a/U+NK+EVERYDAY+CSH+ANKL+3PR+132.png',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Black'],
    rating: 4.5,
    stock: 60,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 110,
    title: 'Nike Heritage Backpack',
    description:
      'Classic design with spacious storage for school, work, or gym.',
    price: 40.0,
    subCategory: 'Accessories',
    category: 'accessories',
    gender: 'unisex',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/21d2731a-9ea7-442a-a968-16f336914b84/NK+HERITAGE+BKPK.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/a3bd9514-8e5a-4371-a179-1e2b7a655ad3/NK+HERITAGE+BKPK.png',
    ],
    sizes: [],
    colors: ['Black', 'Red', 'Blue'],
    rating: 4.6,
    stock: 25,
    isFeatured: true,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Alex Lee',
        rating: 5,
        comment: 'Perfect for daily use and very durable.',
      },
    ],
  },
  {
    id: 201,
    title: 'Nike Pegasus 41',
    description: 'Responsive cushioning and breathable mesh for everyday runs.',
    price: 130.0,
    subCategory: 'shoes',
    category: 'shoes',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/94b25851-20b9-495e-be20-08cda815b08a/AIR+ZOOM+PEGASUS+41.png',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['Black', 'Blue', 'Grey'],
    rating: 4.6,
    stock: 15,
    isFeatured: true,
    isLatest: true,
    reviews: [],
  },
  {
    id: 202,
    title: 'Nike Club Fleece Hoodie',
    description: 'Soft, brushed fleece for warmth and comfort.',
    price: 60.0,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'women',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['Pink', 'White', 'Black'],
    rating: 4.7,
    stock: 25,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 203,
    title: 'Nike Elite Crew Socks (3 Pairs)',
    description: 'Cushioned support and sweat-wicking comfort.',
    price: 22.0,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/hkyn0aqd20fhe7b4xsdb/U+NK+MULTIPLIER+CREW+2PR+CUSH.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f7a0e9a3-21cf-48c3-9360-522c51c502c4/U+NK+MULTIPLIER+CREW+2PR+CUSH.png',
    ],
    sizes: ['M', 'L'],
    colors: ['White', 'Black'],
    rating: 4.4,
    stock: 100,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 204,
    title: 'Nike Sportswear Essential T-Shirt',
    description: 'Everyday tee with soft cotton and bold branding.',
    price: 35.0,
    subCategory: 'tops',
    category: 'clothing',
    gender: 'women',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8d17726e-5b76-41a3-8ee2-c1aa39068e36/AS+M+NSW+TEE+OS+PREM+ESSNTL+FA.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8521174b-be80-4a2a-96d1-af795677fbfc/AS+M+NSW+TEE+OS+PREM+ESSNTL+FA.png',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Grey', 'Black', 'White'],
    rating: 4.3,
    stock: 45,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 205,
    title: 'Nike Flex Stride 2-in-1 Running Shorts',
    description:
      'Lightweight shorts with built-in support and reflective details.',
    price: 50.0,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1de901a6-ceeb-44b9-8ec2-6e46108bc4e0/AS+M+NK+DF+CHALLENGER+5BF+SHO.png',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1de901a6-ceeb-44b9-8ec2-6e46108bc4e0/AS+M+NK+DF+CHALLENGER+5BF+SHO.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4bf7e47c-5300-4d9b-b583-e4c0c4eff11c/AS+M+NK+DF+CHALLENGER+5BF+SHO.png',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Black'],
    rating: 4.5,
    stock: 30,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 206,
    title: 'Nike Air Max Nuaxis',
    description: 'Responsive cushioning and breathable mesh for everyday runs.',
    price: 130.0,
    subCategory: 'shoes',
    category: 'shoes',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6561671e-0ff3-4c20-8463-1ce3b14249dd/NIKE+AIR+MAX+NUAXIS.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/6e665b3a-9a51-4dcc-9ab0-f330044fd99d/NIKE+AIR+MAX+NUAXIS.png',
    ],
    sizes: ['8', '9', '10', '11'],
    colors: ['Black', 'Blue', 'Grey'],
    rating: 4.6,
    stock: 15,
    isFeatured: true,
    isLatest: true,
    reviews: [],
  },
  {
    id: 207,
    title: 'Nike Elite Crew Socks (3 Pairs)',
    description: 'Cushioned support and sweat-wicking comfort.',
    price: 22.0,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/socks-elite-crew.png',
    ],
    sizes: ['M', 'L'],
    colors: ['White', 'Black'],
    rating: 4.4,
    stock: 100,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 208,
    title: 'Nike Flex Stride 2-in-1 Running Shorts',
    description:
      'Lightweight shorts with built-in support and reflective details.',
    price: 50.0,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/flex-stride-shorts.png',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Black'],
    rating: 4.5,
    stock: 30,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 209,
    title: 'Nike Court Vision Low',
    description: 'Retro hoops style updated for the street.',
    price: 75.0,
    subCategory: 'shoes',
    category: 'shoes',
    gender: 'women',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/court-vision-low.png',
    ],
    sizes: ['6', '7', '8', '9'],
    colors: ['White', 'Beige'],
    rating: 4.2,
    stock: 20,
    isFeatured: false,
    isLatest: true,
    reviews: [],
  },
  {
    id: 210,
    title: 'Nike Brasilia Training Backpack',
    description: 'Durable design with ample storage for your daily gear.',
    price: 45.0,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'unisex',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fcdcf1ba-1a2e-4f4e-9de0-e3086b6ca105/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/brasilia-backpack.png',
    ],
    sizes: [],
    colors: ['Black', 'Red', 'Blue'],
    rating: 4.6,
    stock: 80,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 211,
    title: "Nike Pro Dri-FIT Men's Tank",
    description: 'Breathable performance tank for training days.',
    price: 40.0,
    subCategory: 'tops',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fcdcf1ba-1a2e-4f4e-9de0-e3086b6ca105/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/pro-dri-fit-tank.png',
    ],
    sizes: ['M', 'L', 'XL'],
    colors: ['White', 'Black'],
    rating: 4.5,
    stock: 35,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 212,
    title: 'Nike Heritage Waist Pack',
    description: 'Convenient, secure storage in a stylish design.',
    price: 25.0,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'unisex',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/heritage-waist-pack.png',
    ],
    sizes: [],
    colors: ['Black', 'Olive'],
    rating: 4.3,
    stock: 50,
    isFeatured: false,
    isLatest: false,
    reviews: [],
  },
  {
    id: 213,
    title: 'Nike Yoga Luxe Infinalon Leggings',
    description: 'Exceptionally soft and stretchy for studio or street.',
    price: 90.0,
    subCategory: 'bottoms',
    category: 'clothing',
    gender: 'women',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/yoga-luxe-leggings.png',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Lavender'],
    rating: 4.9,
    stock: 22,
    isFeatured: true,
    isLatest: true,
    reviews: [],
  },
  {
    id: 214,
    title: 'Within Tops',
    description: 'Really policy cold strong dream rest present.',
    price: 118.68,
    subCategory: 'tops',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-training-top.png',
    ],
    sizes: ['9', '6', 'L', '8'],
    colors: ['Blue', 'Gray', 'Green'],
    rating: 3.9,
    stock: 82,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Jennifer Newman',
        rating: 5,
        comment: 'Thing cost time show.',
      },
    ],
  },
  {
    id: 215,
    title: 'Red Shorts',
    description: 'Behind important lose general deep follow.',
    price: 45.49,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/53bef953-d2b7-4113-8b79-f2d86feed35a/AIR+ZOOM+PEGASUS+41.png',
    ],
    sizes: ['10', 'M', 'XL', 'S'],
    colors: ['Red', 'Gray', 'Black'],
    rating: 3.7,
    stock: 19,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'John Maddox',
        rating: 4,
        comment: 'Population shake measure concern increase.',
      },
    ],
  },
  {
    id: 216,
    title: 'Involve Shorts',
    description: 'Audience article right wind bad least region.',
    price: 67.13,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-sportswear-shorts.png',
    ],
    sizes: ['6', 'L', 'XL', '7'],
    colors: ['Black', 'White', 'Gray'],
    rating: 4.5,
    stock: 99,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Linda Love',
        rating: 4,
        comment: 'Outside that woman.',
      },
    ],
  },
  {
    id: 217,
    title: 'Actually Shorts',
    description: 'Technology health body its into.',
    price: 130.93,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-sportswear-shorts.png',
    ],
    sizes: ['S', '7', '12', 'XL'],
    colors: ['Red', 'Blue', 'White'],
    rating: 3.6,
    stock: 53,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Jimmy Jones',
        rating: 4,
        comment: 'Get serve own mean program out yes.',
      },
    ],
  },
  {
    id: 218,
    title: 'Approach Shorts',
    description: 'Happy apply move management.',
    price: 82.29,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/club-fleece-shorts.png',
    ],
    sizes: ['12', '10', 'S', 'L'],
    colors: ['White', 'Blue', 'Gray'],
    rating: 3.8,
    stock: 55,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Christian Hawkins',
        rating: 5,
        comment: 'Deep three young appear product.',
      },
    ],
  },
  {
    id: 219,
    title: 'Share Shorts',
    description: 'Effect exist thousand season.',
    price: 98.65,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/club-fleece-shorts.png',
    ],
    sizes: ['8', 'S', '11', 'M'],
    colors: ['Red', 'Blue', 'Pink'],
    rating: 4.2,
    stock: 28,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Courtney Espinoza',
        rating: 5,
        comment: 'Spend doctor me team.',
      },
    ],
  },
  {
    id: 220,
    title: 'He Shorts',
    description: 'Fear size strategy hope six.',
    price: 88.51,
    subCategory: 'shorts',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-sportswear-shorts.png',
    ],
    sizes: ['XL', '12', 'S', '8'],
    colors: ['Pink', 'Black', 'Green'],
    rating: 4.4,
    stock: 30,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Monica Jackson',
        rating: 4,
        comment: 'Person lot give although.',
      },
    ],
  },
  {
    id: 221,
    title: 'Case Hoodies',
    description: 'Close animal because section main information.',
    price: 125.55,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['10', '12', '6', '9'],
    colors: ['Red', 'Blue', 'Gray'],
    rating: 3.6,
    stock: 66,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Tracie Suarez',
        rating: 4,
        comment: 'Night eye above paper.',
      },
    ],
  },
  {
    id: 222,
    title: 'Stay Hoodies',
    description: 'Country must discussion support thus contain.',
    price: 26.11,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['S', '12', '7', 'M'],
    colors: ['Pink', 'Blue', 'Green'],
    rating: 4.6,
    stock: 70,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Sara Bell',
        rating: 5,
        comment: 'Sea send answer simple around.',
      },
    ],
  },
  {
    id: 223,
    title: 'Author Hoodies',
    description: 'Over some tax reach.',
    price: 116.36,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['M', 'S', '12', '6'],
    colors: ['Gray', 'Blue', 'Pink'],
    rating: 4.2,
    stock: 31,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Mary Carter',
        rating: 4,
        comment: 'Increase call recent not ahead again.',
      },
    ],
  },
  {
    id: 224,
    title: 'Country Hoodies',
    description: 'Turn sometimes drive say maintain.',
    price: 80.67,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['6', '8', '12', 'XL'],
    colors: ['Black', 'Green', 'Gray'],
    rating: 3.6,
    stock: 88,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Eddie Harding DDS',
        rating: 5,
        comment: 'Develop interview give.',
      },
    ],
  },
  {
    id: 225,
    title: 'Feeling Hoodies',
    description: 'Reason remember pretty want car.',
    price: 148.99,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['12', 'L', 'S', '6'],
    colors: ['Pink', 'White', 'Green'],
    rating: 4.2,
    stock: 26,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Holly Lee',
        rating: 4,
        comment: 'General again spring sister occur speech age.',
      },
    ],
  },
  {
    id: 226,
    title: 'Hear Hoodies',
    description: 'Remember color go every often agency section.',
    price: 133.48,
    subCategory: 'hoodies',
    category: 'clothing',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/d683aebb-97b5-43bd-b2bb-1d57f35c7412/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ed05e04d-f4d1-49c4-9860-69a6dca841df/AS+M+NK+SOLO+SWSH+FT+PO+HOODIE.png',
    ],
    sizes: ['S', '10', '12', 'M'],
    colors: ['Red', 'Gray', 'White'],
    rating: 4.4,
    stock: 87,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Theodore House',
        rating: 5,
        comment: 'Still daughter finish partner tree.',
      },
    ],
  },
  {
    id: 227,
    title: 'Memory Accessories',
    description: 'No peace effort billion before.',
    price: 126.69,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-cap.png',
    ],
    sizes: ['12', 'XL', 'L', '7'],
    colors: ['White', 'Green', 'Black'],
    rating: 3.7,
    stock: 63,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Patricia Brown',
        rating: 5,
        comment: 'Visit measure individual dream family somebody however easy.',
      },
    ],
  },
  {
    id: 228,
    title: 'Spend Accessories',
    description: 'Nearly environment practice already carry almost let.',
    price: 67.87,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-backpack.png',
    ],
    sizes: ['8', '6', '10', '11'],
    colors: ['Blue', 'Black', 'Pink'],
    rating: 4.4,
    stock: 14,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Victoria Thomas',
        rating: 4,
        comment: 'Kitchen them director successful.',
      },
    ],
  },
  {
    id: 229,
    title: 'Girl Accessories',
    description: 'Recent this skin culture.',
    price: 117.59,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-backpack.png',
    ],
    sizes: ['11', '10', '6', '8'],
    colors: ['Gray', 'Black', 'Pink'],
    rating: 4.9,
    stock: 35,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Mike Cochran',
        rating: 5,
        comment: 'Skin add growth dream these along body affect.',
      },
    ],
  },
  {
    id: 230,
    title: 'Among Accessories',
    description: 'Player measure time.',
    price: 42.82,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-cap.png',
    ],
    sizes: ['11', '6', '9', '12'],
    colors: ['Pink', 'Black', 'Red'],
    rating: 3.8,
    stock: 83,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Harold Cook',
        rating: 5,
        comment: 'Situation edge seat nature myself when believe.',
      },
    ],
  },
  {
    id: 231,
    title: 'Song Accessories',
    description: 'Bill the read hot opportunity.',
    price: 56.04,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-cap.png',
    ],
    sizes: ['M', '11', '9', '12'],
    colors: ['Black', 'Red', 'Blue'],
    rating: 3.6,
    stock: 36,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Lindsay Adams',
        rating: 4,
        comment: 'Billion field speak could film skin.',
      },
    ],
  },
  {
    id: 232,
    title: 'Light Accessories',
    description: 'Anyone suggest direction whether you your.',
    price: 126.87,
    subCategory: 'accessories',
    category: 'accessories',
    gender: 'men',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/nike-backpack.png',
    ],
    sizes: ['S', '6', '10', '8'],
    colors: ['Red', 'White', 'Gray'],
    rating: 4.4,
    stock: 10,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Tommy Weaver',
        rating: 5,
        comment: 'Like call yeah change.',
      },
    ],
  },
  {
    id: 233,
    title: 'Alone Kids',
    description: 'Course arm at worker sure voice.',
    price: 83.82,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/h_599,c_limit/a5d40706-5d3b-4ebf-9352-b3b0faeba204/air-jordan-1-low-older-shoes-xLzJc6.png',
    images: [
      'https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/h_599,c_limit/a5d40706-5d3b-4ebf-9352-b3b0faeba204/air-jordan-1-low-older-shoes-xLzJc6.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/b543715a-24e2-464e-94cf-07981f872fed/AIR+JORDAN+1+LOW+%28GS%29.png',
    ],
    sizes: ['7', 'M', '11', '9'],
    colors: ['Pink', 'White', 'Green'],
    rating: 3.6,
    stock: 32,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Jacob Park',
        rating: 4,
        comment: 'Practice American matter.',
      },
    ],
  },
  {
    id: 234,
    title: 'War Kids',
    description: 'Down them group simply mouth.',
    price: 127.49,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    iconImg:
      'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a64ffe44-e504-46b5-b5da-e93edad2d6ab/B+NK+DF+SS+MILER+TOP.png',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/64ff2848-6ccf-4361-b314-e7ddef820340/B+NK+DF+SS+MILER+TOP.png',
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/64ff2848-6ccf-4361-b314-e7ddef820340/B+NK+DF+SS+MILER+TOP.png',
    ],
    sizes: ['9', '12', 'M', 'L'],
    colors: ['Blue', 'Black', 'Green'],
    rating: 4.7,
    stock: 88,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'James Moran',
        rating: 4,
        comment: 'Me local everything fill.',
      },
    ],
  },
  {
    id: 235,
    title: 'Population Kids',
    description: 'Democratic trip then.',
    price: 119.52,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/kids-running-shoes.png',
    ],
    sizes: ['XL', '9', '12', '10'],
    colors: ['Pink', 'Blue', 'Gray'],
    rating: 4.7,
    stock: 74,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Amy Smith',
        rating: 4,
        comment: 'Soldier between another artist member ability human.',
      },
    ],
  },
  {
    id: 236,
    title: 'Total Kids',
    description: 'Wait increase evening doctor down.',
    price: 86.3,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/kids-running-shoes.png',
    ],
    sizes: ['11', 'XL', '8', '6'],
    colors: ['Gray', 'Green', 'Black'],
    rating: 4.7,
    stock: 56,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Anita Thompson',
        rating: 4,
        comment: 'Determine sign various leg.',
      },
    ],
  },
  {
    id: 237,
    title: 'Direction Kids',
    description: 'Hour play six daughter provide.',
    price: 70.41,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/kids-graphic-tshirt.png',
    ],
    sizes: ['6', '11', '7', '9'],
    colors: ['Black', 'Green', 'Red'],
    rating: 3.6,
    stock: 39,
    isFeatured: false,
    isLatest: false,
    reviews: [
      {
        id: 1,
        user: 'Daniel Patterson',
        rating: 4,
        comment: 'Drive moment worry wish dream.',
      },
    ],
  },
  {
    id: 238,
    title: 'Mr Kids',
    description: 'Street people task.',
    price: 136.84,
    subCategory: 'kids',
    gender: 'kids',
    brand: 'Nike',
    images: [
      'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/kids-running-shoes.png',
    ],
    sizes: ['10', '8', 'S', 'XL'],
    colors: ['Red', 'Blue', 'White'],
    rating: 4.8,
    stock: 62,
    isFeatured: true,
    isLatest: true,
    reviews: [
      {
        id: 1,
        user: 'Dominique Miller',
        rating: 5,
        comment: 'Sport far offer particular.',
      },
    ],
  },
];
